### ISSUE TITLE
CA injection via cert-manager in ClusterSecretStore do not work

### ISSUE THREAD

**Issue by volschin** [external-secrets/bitwarden-sdk-server#9]
**Describe the bug**
I tried to setup ClusterSecretStore after deployment of the self signed certificate chain and the helm installation. I tried to inject the ca instead of using the caBundle field statically.
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
  annotations:
    cert-manager.io/inject-ca-from: external-secrets/bitwarden-tls-certs
```
But it tells me caBundle is a required field.
Full message from reconciliation:
```
ClusterSecretStore/external-secrets/bitwarden-secrets-manager dry-run failed (Invalid): ClusterSecretStore.external-secrets.io "bitwarden-secrets-manager" is invalid: spec.provider.bitwardensecretsmanager.caBundle: Required value
```

**To Reproduce**
My deployment is made with flux. My yaml code can be seen here:
https://github.com/volschin/home-ops/blob/main/kubernetes/apps/external-secrets/external-secrets/stores/bitwarden-secrets/clustersecretstore.yaml

**Expected behavior**
It should be possible to inject the ca from the generated certificate in the ClusterSecretStore.

** Additional **
In my connected research I found this linkerd issue an pr from some years ago that goes in a same direction an perhaps helps.
https://github.com/linkerd/linkerd2/issues/7353
